// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          account_number_last4: string | null;
          avatar_url: string | null;
          bank_account_name: string | null;
          bank_name: string | null;
          business_name: string | null;
          created_at: string | null;
          date_of_birth: string | null;
          district: string | null;
          farm_size: number | null;
          full_name: string | null;
          gender: string | null;
          id: string;
          mobile: string | null;
          notifications: boolean | null;
          payment_methods: string[] | null;
          phone: string | null;
          pincode: string | null;
          primary_crops: string[] | null;
          soil_type: string | null;
          state: string | null;
          theme: string | null;
          upi_id: string | null;
          user_id: string;
          village: string | null;
        };
        Insert: {
          account_number_last4?: string | null;
          avatar_url?: string | null;
          bank_account_name?: string | null;
          bank_name?: string | null;
          business_name?: string | null;
          created_at?: string | null;
          date_of_birth?: string | null;
          district?: string | null;
          farm_size?: number | null;
          full_name?: string | null;
          gender?: string | null;
          id?: string;
          mobile?: string | null;
          notifications?: boolean | null;
          payment_methods?: string[] | null;
          phone?: string | null;
          pincode?: string | null;
          primary_crops?: string[] | null;
          soil_type?: string | null;
          state?: string | null;
          theme?: string | null;
          upi_id?: string | null;
          user_id: string;
          village?: string | null;
        };
        Update: {
          account_number_last4?: string | null;
          avatar_url?: string | null;
          bank_account_name?: string | null;
          bank_name?: string | null;
          business_name?: string | null;
          created_at?: string | null;
          date_of_birth?: string | null;
          district?: string | null;
          farm_size?: number | null;
          full_name?: string | null;
          gender?: string | null;
          id?: string;
          mobile?: string | null;
          notifications?: boolean | null;
          payment_methods?: string[] | null;
          phone?: string | null;
          pincode?: string | null;
          primary_crops?: string[] | null;
          soil_type?: string | null;
          state?: string | null;
          theme?: string | null;
          upi_id?: string | null;
          user_id?: string;
          village?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      experts: {
        Row: {
          id: string;
          name: string;
          specialty: string;
          bio: string | null;
          experience_years: number | null;
          rating: number;
          reviews_count: number;
          daily_rate: number;
          monthly_rate: number;
          availability_status: string;
          image_url: string | null;
          phone: string | null;
          email: string | null;
          languages: string[] | null;
          certifications: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          specialty: string;
          bio?: string | null;
          experience_years?: number | null;
          rating?: number;
          reviews_count?: number;
          daily_rate?: number;
          monthly_rate?: number;
          availability_status?: string;
          image_url?: string | null;
          phone?: string | null;
          email?: string | null;
          languages?: string[] | null;
          certifications?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          specialty?: string;
          bio?: string | null;
          experience_years?: number | null;
          rating?: number;
          reviews_count?: number;
          daily_rate?: number;
          monthly_rate?: number;
          availability_status?: string;
          image_url?: string | null;
          phone?: string | null;
          email?: string | null;
          languages?: string[] | null;
          certifications?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      expert_bookings: {
        Row: {
          id: string;
          user_id: string;
          expert_id: string;
          booking_date: string;
          duration: "daily" | "monthly";
          total_amount: number;
          status: "pending" | "confirmed" | "completed" | "cancelled";
          payment_status: "pending" | "completed" | "failed";
          notes: string | null;
          meeting_link: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          expert_id: string;
          booking_date: string;
          duration: "daily" | "monthly";
          total_amount: number;
          status?: "pending" | "confirmed" | "completed" | "cancelled";
          payment_status?: "pending" | "completed" | "failed";
          notes?: string | null;
          meeting_link?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          expert_id?: string;
          booking_date?: string;
          duration?: "daily" | "monthly";
          total_amount?: number;
          status?: "pending" | "confirmed" | "completed" | "cancelled";
          payment_status?: "pending" | "completed" | "failed";
          notes?: string | null;
          meeting_link?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "expert_bookings_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "expert_bookings_expert_id_fkey";
            columns: ["expert_id"];
            isOneToOne: false;
            referencedRelation: "experts";
            referencedColumns: ["id"];
          }
        ];
      };
      expert_reviews: {
        Row: {
          id: string;
          expert_id: string;
          user_id: string;
          booking_id: string | null;
          rating: number | null;
          review_text: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          expert_id: string;
          user_id: string;
          booking_id?: string | null;
          rating?: number | null;
          review_text?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          expert_id?: string;
          user_id?: string;
          booking_id?: string | null;
          rating?: number | null;
          review_text?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "expert_reviews_expert_id_fkey";
            columns: ["expert_id"];
            isOneToOne: false;
            referencedRelation: "experts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "expert_reviews_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "expert_reviews_booking_id_fkey";
            columns: ["booking_id"];
            isOneToOne: false;
            referencedRelation: "expert_bookings";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
